keppler_catalogs/config/routes.rb
KepplerCatalogs::Engine.routes.draw do
  
  scope :admin do

  	resources :catalogs do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      resources :attachments do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end
    end

    scope :attachment do
    	resources :categories do
    		get '(page/:page)', action: :index, on: :collection, as: ''
      		delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    	end
    end
  end


    
end

keppler_catalogs/app/models/keppler_catalogs/attachment.rb
#Generado por keppler
require 'elasticsearch/model'
module KepplerCatalogs
  class Attachment < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    belongs_to :catalog
    belongs_to :category
    before_save :create_permalink, :if => :new_record?
    has_many :attachment_images, :dependent => :destroy
    has_many :plans, :dependent => :destroy
    accepts_nested_attributes_for :attachment_images, :allow_destroy => true, :reject_if => :all_blank
    accepts_nested_attributes_for :plans, :allow_destroy => true, :reject_if => :all_blank
    validates_presence_of :name, :subtitle, :category
    mount_uploader :date_image, ImageUploader
    validates_presence_of :attachment_images

    
    after_commit on: [:update] do
      __elasticsearch__.index_document
    end



    def self.searching(query)
      if query
        self.search(self.query query).records.order(id: :desc)
      else
        self.order(id: :desc)
      end
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:name, :description, :category, :public] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    #armar indexado de elasticserch
    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        name:  self.name,
        description: ActionView::Base.full_sanitizer.sanitize(self.description, tags: []),
        category: self.category.name,
        public:  self.public ? "publicado" : "no--publicado"
      }.as_json
    end

    def create_permalink
      self.permalink = "#{self.name.downcase.parameterize}-#{SecureRandom.hex(3)}"
    end

  end
  #Attachment.import
end

keppler_catalogs/app/models/keppler_catalogs/attachment_image.rb
module KepplerCatalogs
  class AttachmentImage < ActiveRecord::Base
  	mount_uploader :image, ImageUploader
  	belongs_to :attachment
  end
end

keppler_catalogs/app/models/keppler_catalogs/catalog.rb
#Generado por keppler
require 'elasticsearch/model'
module KepplerCatalogs
  class Catalog < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    mount_uploader :cover, CoverUploader
    before_save :create_permalink
    has_many :attachments, :dependent => :destroy
    validates_presence_of :title, :section    
    validates_length_of :title, :minimum => 1, :maximum => 40

    after_commit on: [:update] do
      puts __elasticsearch__.index_document
    end

    def attachments_publised
      self.attachments.where(public:true)
    end
    
    def self.searching(query)
      if query
        self.search(self.query query).records.order(id: :desc)
      else
        self.order(id: :desc)
      end
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:title, :description, :section, :public] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        title:  self.title.to_s,
        description: ActionView::Base.full_sanitizer.sanitize(self.description, tags: []),
        section:  self.section,
        public:  self.public.to_s ? "publicado": "no--publicado"
      }.as_json
    end
    
    def published_files
      self.attachments.where(public: true)
    end

    def published_files_count
      self.attachments.where(public: true).count
    end

    private

    def create_permalink
      self.permalink = self.title.downcase.parameterize
    end

  end
  #Catalog.import
end

keppler_catalogs/app/models/keppler_catalogs/category.rb
#Generado por keppler
require 'elasticsearch/model'
module KepplerCatalogs
  class Category < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    before_save :create_permalink
    has_many :attachments, :dependent => :destroy
    validates_presence_of :name
    
    after_commit on: [:update] do
      puts __elasticsearch__.index_document
    end 
    
    def self.searching(query)
      if query
        self.search(self.query query).records.order(id: :desc)
      else
        self.order(id: :desc)
      end
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:id, :name] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    #armar indexado de elasticserch
    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        name: self.name
      }.as_json
    end

    private

    def create_permalink
      self.permalink = self.name.downcase.parameterize
    end

  end
  #Category.import
end

keppler_catalogs/app/models/keppler_catalogs/plan.rb
module KepplerCatalogs
  class Plan < ActiveRecord::Base
  	belongs_to :attachment
  end
end

keppler_catalogs/app/controllers/keppler_catalogs/application_controller.rb
module KepplerCatalogs
  class ApplicationController < ActionController::Base
  end
end

keppler_catalogs/app/controllers/keppler_catalogs/attachments_controller.rb
#Generado con Keppler.
require_dependency "keppler_catalogs/application_controller"

module KepplerCatalogs
  class AttachmentsController < ::ApplicationController  
    before_filter :authenticate_user!
    layout 'admin/application'
    load_and_authorize_resource
    before_action :set_attachment, only: [:show, :edit, :update, :destroy]
    before_action :set_catalog

    # GET /attachments
    def index
      attachments = Attachment.searching(@query).where({catalog_id: params[:catalog_id]}).all
      @objects, @total = attachments.page(@current_page), attachments.size
      redirect_to attachments_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
    end

    # GET /attachments/1
    def show
    end

    # GET /attachments/new
    def new
      @attachment = Attachment.new
    end

    # GET /attachments/1/edit
    def edit
    end

    # POST /attachments
    def create
      @attachment = Attachment.new(attachment_params)
      @attachment.catalog_id = params[:catalog_id]

      if @attachment.save
        redirect_to catalog_attachments_path, notice: 'Archivo creado satisfactoriamente.'
      else
        render :new
      end
    end

    # PATCH/PUT /attachments/1
    def update
      if params[:remove_image].eql? "1"
        @attachment.remove_date_image!
      end

      if @attachment.update(attachment_params)
        redirect_to catalog_attachments_path, notice: 'Archivo editado satisfactoriamente.'
      else
        render :edit
      end
    end

    # DELETE /attachments/1
    def destroy
      @attachment.destroy
      redirect_to catalog_attachments_url, notice: 'Archivo eliminado satisfactoriamente.'
    end

    def destroy_multiple
      Attachment.destroy redefine_ids(params[:multiple_ids])
      redirect_to catalog_attachments_path(page: @current_page, search: @query), notice: "Archivo eliminados satisfactoriamente" 
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_attachment
        @attachment = Attachment.find(params[:id])
      end

      def set_catalog
        @catalog = Catalog.find_by_id(params[:catalog_id]).nil? ? redirect_to("/404") : Catalog.find(params[:catalog_id])
      end

      # Only allow a trusted parameter "white list" through.
      def attachment_params
        params.require(:attachment).permit(:name, :subtitle, :price, :number_of_days, :next_exit, :opcional, :map, :notes, :date_image, :remove_image, :no_include_plan, :include_plan, :description, :itinerary, :url, :public, :permalink, :category_id, attachment_images_attributes: [:id, :image, :_destroy], plans_attributes: [:id, :name, :url, :_destroy])
      end
  end
end

keppler_catalogs/app/controllers/keppler_catalogs/catalogs_controller.rb
#Generado con Keppler.
require_dependency "keppler_catalogs/application_controller"

module KepplerCatalogs
  class CatalogsController < ::ApplicationController  
    before_filter :authenticate_user!
    layout 'admin/application'
    load_and_authorize_resource
    before_action :set_catalog, only: [:show, :edit, :update, :destroy]

    # GET /catalogs
    def index
      catalogs = Catalog.searching(@query).all
      @objects, @total = catalogs.page(@current_page), catalogs.size
      redirect_to catalogs_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
    end

    # GET /catalogs/1
    def show
    end

    # GET /catalogs/new
    def new
      @catalog = Catalog.new
    end

    # GET /catalogs/1/edit
    def edit
    end

    # POST /catalogs
    def create
      @catalog = Catalog.new(catalog_params)

      if @catalog.save
        redirect_to catalogs_path, notice: 'Catálogo creado satisfactoriamente.'
      else
        render :new
      end
    end

    # PATCH/PUT /catalogs/1
    def update
      if @catalog.update(catalog_params)
        redirect_to catalogs_path, notice: 'Catálogo editar satisfactoriamente.'
      else
        render :edit
      end
    end

    # DELETE /catalogs/1
    def destroy
      @catalog.destroy
      redirect_to catalogs_url, notice: 'Catálogo eliminar satisfactoriamente.'
    end

    def destroy_multiple
      Catalog.destroy redefine_ids(params[:multiple_ids])
      redirect_to catalogs_path(page: @current_page, search: @query), notice: "Catalogos eliminados satisfactoriamente" 
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_catalog
        @catalog = Catalog.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def catalog_params
        params.require(:catalog).permit(:cover, :title, :description, :section, :public, :permalink)
      end
  end
end

keppler_catalogs/app/controllers/keppler_catalogs/categories_controller.rb
#Generado con Keppler.
require_dependency "keppler_catalogs/application_controller"

module KepplerCatalogs
  class CategoriesController < ::ApplicationController  
    before_filter :authenticate_user!
    layout 'admin/application'
    load_and_authorize_resource
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    # GET /categories
    def index
      categories = Category.searching(@query).all
      @objects, @total = categories.page(@current_page), categories.size
      redirect_to categories_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
    end

    # GET /categories/1
    def show
    end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories
    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to @category, notice: 'Categoria creada satisfactoriamente.'
      else
        render :new
      end
    end

    # PATCH/PUT /categories/1
    def update
      if @category.update(category_params)
        redirect_to @category, notice: 'Categoria editada satisfactoriamente.'
      else
        render :edit
      end
    end

    # DELETE /categories/1
    def destroy
      @category.destroy
      redirect_to categories_url, notice: 'Categoria eliminada satisfactoriamente.'
    end

    def destroy_multiple
      Category.destroy redefine_ids(params[:multiple_ids])
      redirect_to categories_path(page: @current_page, search: @query), notice: "Categorias eliminados satisfactoriamente" 
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def category_params
        params.require(:category).permit(:name, :permalink)
      end
  end
end

keppler_catalogs/app/helpers/keppler_catalogs/application_helper.rb
module KepplerCatalogs
  module ApplicationHelper
  end
end

keppler_catalogs/app/helpers/keppler_catalogs/attachments_helper.rb
module KepplerCatalogs
  module AttachmentsHelper
  end
end

keppler_catalogs/app/helpers/keppler_catalogs/catalogs_helper.rb
module KepplerCatalogs
  module CatalogsHelper
  end
end

keppler_catalogs/app/helpers/keppler_catalogs/categories_helper.rb
module KepplerCatalogs
  module CategoriesHelper
  end
end

keppler_catalogs/app/views/keppler_catalogs/attachments/_attachment_image_fields.html.haml
%li.collection-item.avatar.nested-fields
	= image_tag f.object.image, width: "48px;", class: "circle"
	= f.input :image, label: t("model.#{controller_name.singularize}.attributes.cover"), :as => :file_material, label: false, wrapper_html: { class: "file-field", id: "image-#{f.object.id}"}
	= link_to_remove_association "<i class='material-icons md-24'>delete</i>".html_safe, f, class: "secondary-content"
	- if f.object.created_at?
		:javascript
			$("#image-#{f.object.id} .file-path").val("#{f.object.image_identifier}")

keppler_catalogs/app/views/keppler_catalogs/attachments/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.perm_media.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 
			= t("model.#{controller_name.singularize}.description.title")
		%p{align:"justify"} 
			= t("model.#{controller_name.singularize}.description.body")

keppler_catalogs/app/views/keppler_catalogs/attachments/_form.html.haml
- (action_name == "new" or action_name == "create") ? action="create" : action="update"

.wrapper
	.wrapper-body.container
		.actions
			= link_to catalog_attachments_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			
			.card
				= simple_form_for @attachment, :url => url_for(:action => action, :controller => 'attachments') do |f|
					.row
						= f.input :name, label: t("model.#{controller_name.singularize}.attributes.name")	

						= f.input :subtitle, label: t("model.#{controller_name.singularize}.attributes.subtitle")				

						= f.input :price, label: t("model.#{controller_name.singularize}.attributes.price")

						= f.input :number_of_days, label: t("model.#{controller_name.singularize}.attributes.number_of_days")

						= f.input :next_exit, label: t("model.#{controller_name.singularize}.attributes.next_exit")

						= f.association :category, label: false,include_blank: "- Selecciona una categoria -", input_html: { class: "browser-default", style: "margin-bottom: 30px;" }	

						%h6{style: "color: #9e9e9e; margin-top:15px; margin-left:10px;"} Planes
						%ul.collection{ style: "margin: 5px 10px;"}
							= f.simple_fields_for :plans do |plan|
								= render 'plan_fields', f: plan
							%center{ style: "padding: 20px;"}
								= link_to_add_association 'Añadir Plan', f, :plans, class: "waves-light btn", style: "width: 100%"

						= f.input :map, input_html: {class: "materialize-textarea"}, label: t("model.#{controller_name.singularize}.attributes.map")

						%h6{style: "color: #9e9e9e; margin-top:15px; margin-left:10px;"} Descripcion
						= f.input :notes, :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'short'} }	

						%h6{style: "color: #9e9e9e; margin-top:15px; margin-left:10px; position:relative; top: 10px;"} Importante
						= f.input :description, :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'short'} }

						%h6{style: "color: #9e9e9e; margin-top:15px; margin-left:10px;"} Opcional
						= f.input :opcional, :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'short'} }	

						%h6{style: "color: #9e9e9e; margin-top:15px; margin-left:10px; position:relative; top: 12px;"} ¿Qué incluye el plan?
						= f.input :include_plan, :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'short'} }	

						%h6{style: "color: #9e9e9e; margin-top:15px; margin-left:10px;"} ¿Qué no incluye el plan?
						= f.input :no_include_plan, :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'short'} }	
						
						= f.input :itinerary, :as => :ckeditor, label: "Itinerario del viaje", input_html: { :ckeditor => { :toolbar => 'short'} }

						- if action_name == "update" or action_name == "edit" and @attachment.date_image.file
							%h6.right-align{style: "color: #000; display: inline; float: right; position: relative; left: -10px;"} Eliminar imagen
							.switch{style:"float: right; position: relative; top: 3px"}
								%label
									= check_box_tag :remove_image
									%span.lever
							

						= f.input :date_image, :as => :file_material, label: false, wrapper_html: { class: "file-field" }

					.row
						%h6{style: "color: #9e9e9e; margin-top:15px; margin-left:10px;"} Imagenes
						%ul.collection{ style: "margin: 5px 10px;"}
							= f.simple_fields_for :attachment_images do |image|
								= render 'attachment_image_fields', f: image
							%center{ style: "padding: 20px;"}
								= link_to_add_association 'Añadir Imagen', f, :attachment_images, class: "waves-light btn", style: "width: 100%"
						= f.input :public, label: "¿Desea publicar este archivo?", as: :checkbox_material	
							

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"


- if @attachment.date_image.file
	:javascript
		$('.file-path').val("#{@attachment.date_image.file.filename}")

keppler_catalogs/app/views/keppler_catalogs/attachments/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, model
			= link_to edit_catalog_attachment_path(params[:catalog_id], @attachment), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", "data-no-turbolink" => true do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.perm_media.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.slider
		%ul.slides
			- @attachment.attachment_images.each do |img|
				%li
					= image_tag img.image
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @attachment.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.price")
			.display-value= @attachment.price
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.number_of_days")
			.display-value= @attachment.number_of_days
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.description")
			.display-value= sanitize(@attachment.description, tags: []).truncate(300)
		-if @attachment.category.name?
			%li.list-row
				.display-label= t("model.#{controller_name.singularize}.attributes.category")
				.display-value= @attachment.category.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.public")
			.display-value= @attachment.public? ? "Si" : "No"	

:javascript
	$('.tooltipped').tooltip({delay: 1});
	$('.slider').slider({full_width: true, height: 200});

keppler_catalogs/app/views/keppler_catalogs/attachments/_listing.html.haml
%tr{ id: "row-#{attachment.id}" }
	- if can? :destroy_multiple, model
		%td.item-check{style:"width: 10%"}
			= link_to "", catalog_attachment_path(params[:catalog_id], attachment), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{attachment.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{attachment.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{attachment.id}" }

	%td{style:"width: 30%"}
		= link_to "", catalog_attachment_path(params[:catalog_id], attachment.id, search: @query), remote: true, class: "show-row"
		%span
			= attachment.name

	%td{style:"width: 30%"}
		= link_to "", catalog_attachment_path(params[:catalog_id], attachment.id, search: @query), remote: true, class: "show-row"
		%span
			= attachment.category.name

	%td{style:"width: 30%"}
		= link_to "", catalog_attachment_path(params[:catalog_id], attachment, search: @query), remote: true, class: "show-row"
		%span
			- if attachment.public?
				Publicado
			- else
				No Publicado
								
	%td{style:"width: 5%"}		
		= link_to catalog_attachment_path(params[:catalog_id], attachment), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

keppler_catalogs/app/views/keppler_catalogs/attachments/_mediaframe.html.haml
- if attachment.image?
	= image_tag attachment.image, style:"#{style}"
- elsif attachment.url? and attachment.upload.to_i == 2
	= image_tag attachment.url, style:"#{style}"
- elsif attachment.url? and attachment.upload.to_i == 3
	%iframe.video-player.img-responsive{:allowfullscreen => "", :frameborder => "0",:src =>"#{attachment.url}", style:"#{style}"}

keppler_catalogs/app/views/keppler_catalogs/attachments/_plan_fields.html.haml
%li.collection-item.avatar.nested-fields{style:"min-height: 180px;"}
	= f.input :name, label: "Nombre del plan", wrapper_html: { class: "file-field", id: "image-#{f.object.id}"}
	= f.input :url, label: "Enlace del plan", wrapper_html: { class: "file-field", id: "image-#{f.object.id}"}
	= link_to_remove_association "<i class='material-icons md-24'>delete</i>".html_safe, f, class: "secondary-content"

keppler_catalogs/app/views/keppler_catalogs/attachments/edit.html.haml
= title "Archivo - editar | #{@attachment.id}"
= header_information do
	= link_to "Catálogos", catalogs_path
	= ">"
	= link_to "#{@catalog.title.humanize}", catalog_attachments_path
	= "> #{@attachment.name.humanize}"

= render 'form'

keppler_catalogs/app/views/keppler_catalogs/attachments/index.html.haml
= title("#{@catalog.title.humanize} - Archivos - Listado")

//change header information
= header_information do
	= link_to "Catálogos", catalogs_path
	= "> #{@catalog.title.humanize}"

.listing.col.l9.m12.s12
	- if can? :new, KepplerCatalogs::Attachment
		= link_to new_catalog_attachment_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only", "data-no-turbolink" => false do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |attachment|
				= render 'listing', attachment: attachment
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t("model.#{controller_name.singularize}.no_found.text")
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, KepplerCatalogs::Attachment
	= link_to new_catalog_attachment_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red", "data-no-turbolink" => false do
		= material_icon.md_24.add.css_class("md-light")

keppler_catalogs/app/views/keppler_catalogs/attachments/new.html.haml
= title "Archivo - Nuevo"
= header_information do
	= link_to "Catálogos", catalogs_path
	= "> #{@catalog.title.humanize} "
= render 'form'

keppler_catalogs/app/views/keppler_catalogs/attachments/show.html.haml
= title "Archivo | #{@attachment.id}"
= header_information do
	= link_to "Catálogos", catalogs_path
	= ">"
	= link_to "#{@catalog.title.humanize}", catalog_attachments_path
	= "> #{@attachment.name.humanize}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, model
				= link_to catalog_attachment_path(params[:catalog_id], @attachment), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, model
				= link_to edit_catalog_attachment_path(params[:catalog_id], @attachment), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", "data-no-turbolink" => true do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to catalog_attachments_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card{style: "padding: 0px"}		
			.card-image
				.slider
					%ul.slides
						- @attachment.attachment_images.each do |img|
							%li
								= image_tag img.image
			.card-content
				%ul.list
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.name")
						.display-value.fs-body-1.tc-black-2= @attachment.name.humanize
					-if @attachment.category.name
						%li.list-row
							.display-label= t("model.#{controller_name.singularize}.attributes.category")
							.display-value.fs-body-1.tc-black-2= @attachment.category.name.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.price")
						.display-value.fs-body-1.tc-black-2= @attachment.price
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.number_of_days")
						.display-value.fs-body-1.tc-black-2= @attachment.next_exit
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.number_of_days")
						.display-value.fs-body-1.tc-black-2= @attachment.number_of_days
					%li.list-row
						.display-label= "Enlaces de planes"
						- @attachment.plans.each do |plan|
							.display-value.fs-body-1.tc-black-2= plan.name
							%br
							.display-value.fs-body-1.tc-black-2= plan.url
							%br
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.map")
						.display-value.fs-body-1.tc-black-2= @attachment.map
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.notes")
						.display-value.fs-body-1.tc-black-2= @attachment.notes
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.description")
						.display-value.fs-body-1.tc-black-2= @attachment.description.html_safe
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.include_plan")
						.display-value.fs-body-1.tc-black-2= @attachment.include_plan.html_safe
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.no_include_plan")
						.display-value.fs-body-1.tc-black-2= @attachment.no_include_plan.html_safe
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.itinerary")
						.display-value.fs-body-1.tc-black-2= @attachment.itinerary.html_safe
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.date_image")
						.card-image
							= image_tag @attachment.date_image
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.public")
						.display-value.fs-body-1.tc-black-2= @attachment.public? ? "Si" : "No"
	

keppler_catalogs/app/views/keppler_catalogs/attachments/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@attachment.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");